# Generated by Django 2.1.4 on 2019-01-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clg_list',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clg_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='cutt_offs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fcutt', models.IntegerField()),
                ('tcutt', models.IntegerField()),
                ('ficutt', models.IntegerField()),
                ('scutt', models.IntegerField()),
            ],
            options={
                'db_table': 'cutt_offs',
            },
        ),
        migrations.CreateModel(
            name='sipna_direct_cutt_offs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(max_length=50)),
                ('GOPEN', models.IntegerField(blank=True, null=True)),
                ('LOPEN', models.IntegerField(blank=True, null=True)),
                ('GOBC', models.IntegerField(blank=True, null=True)),
                ('GSC', models.IntegerField(blank=True, null=True)),
                ('GST', models.IntegerField(blank=True, null=True)),
                ('GNTA', models.IntegerField(blank=True, null=True)),
                ('LNTA', models.IntegerField(blank=True, null=True)),
                ('GNTD', models.IntegerField(blank=True, null=True)),
                ('LNTC', models.IntegerField(blank=True, null=True)),
                ('DEF', models.IntegerField(blank=True, null=True)),
                ('PHC', models.IntegerField(blank=True, null=True)),
                ('OPEN', models.IntegerField(blank=True, null=True)),
                ('GNTB', models.IntegerField(blank=True, null=True)),
                ('LSC', models.IntegerField(blank=True, null=True)),
                ('LVJDT', models.IntegerField(blank=True, null=True)),
                ('GVJDT', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sipna_direct_cutt_offs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tfws_clg_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('intake', models.IntegerField(blank=True, null=True)),
                ('clg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.clg_list')),
            ],
            options={
                'db_table': 'tfws_clg_list',
                'managed': True,
            },
        ),
    ]
