# Generated by Django 2.1.7 on 2019-03-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_predict_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='first_predict_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_id', models.IntegerField(blank=True, null=True)),
                ('branch', models.CharField(max_length=100)),
                ('cate', models.CharField(max_length=100)),
                ('per_13', models.IntegerField(blank=True, null=True)),
                ('per_15', models.IntegerField(blank=True, null=True)),
                ('per_16', models.IntegerField(blank=True, null=True)),
                ('per_17', models.IntegerField(blank=True, null=True)),
                ('per_18', models.IntegerField(blank=True, null=True)),
                ('cuttoff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'first_predict_table',
                'managed': True,
            },
        ),
    ]
